# require:
#   - rubocop-rails
#   - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  SuggestExtensions: false

#   Exclude:
#     - db/**/*
#     - bin/*
#     - config/**/*
#     - config.ru

# Documentation:
#   Enabled: false

# Lint/AmbiguousBlockAssociation:
#   Enabled: false

# Metrics/LineLength:
#   Max: 120
  # Exclude:

# Metrics/BlockLength:
#   Exclude:
#     - spec/**/*.rb

# Style/ClassAndModuleChildren:
#   Exclude: 
#     - test/test_helper.rb