woo_manage_products_api_connifo: &woocommerce_manage_products_api_connifo
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000

development:
  <<: *woocommerce_manage_products_api_connifo
  database: 'woocommerce_manage_products'

test:
  <<: *woocommerce_manage_products_api_connifo
  database: <%= 'woocommerce_manage_products_test' + ENV.fetch("TEST_ENV_NUMBER", '') %>
