categories_cleanup_job:
  cron: "0 1 * * *"
  class: "CategoriesCleanupJob"
  queue: cleanup

products_cleanup_job:
  cron: "10 1 * * *"
  class: "ProductsCleanupJob"
  queue: cleanup

attachments_fix_job:
  cron: "0 4 * * *"
  class: "AttachmentsFixJob"
  queue: attachments_fix

products_update_price_job:
  cron: "0 3 * * *"
  class: "ProductsUpdatePriceJob"
  queue: products_iteration
