categories_cleanup_job:
  cron: "0 1 * * *"
  class: "CategoriesCleanupJob"
  queue: cleanup

products_cleanup_job:
  cron: "10 1 * * *"
  class: "ProductsCleanupJob"
  queue: cleanup

  #   mgr.register("0 1 * * *", "CategoriesCleanupJob") # Category cleanup every day at 1 am
#   mgr.register("10 1 * * *", "ProductsCleanupJob") # Product cleanup every day at 1:10 am