categories_cleanup_job:
  cron: "0 19 * * 1,3,5"
  class: "CategoriesCleanupJob"
  queue: cleanup
  enabled: false

argentina_categories_cleanup_job:
  cron: "0 19 * * 1,3,5"
  class: "ArgentinaCategoriesCleanupJob"
  queue: cleanup
  enabled: false

chile_categories_cleanup_job:
  cron: "0 19 * * 1,3,5"
  class: "ChileCategoriesCleanupJob"
  queue: cleanup
  enabled: false

products_cleanup_job:
  cron: "15 19 * * 1,3,5"
  class: "ProductsCleanupJob"
  queue: cleanup
  enabled: false

categories_setup_job:
  cron: "5 19 * * 1,3,5"
  class: "CategoriesSetupJob"
  queue: categories
  enabled: false

products_iteration_job:
  cron: "30 19 * * 1,3,5"
  class: "ProductsIterationJob"
  queue: products_iteration
  enabled: false

attachments_fix_job:
  cron: "0 23 * * 1,3,5"
  class: "AttachmentsFixJob"
  queue: attachments_fix
  enabled: false

products_update_price_job:
  cron: "0 20 * * 1,3,5"
  class: "ProductsUpdatePriceJob"
  queue: products_iteration
  enabled: false

product_customization_job:
  cron: "0 21 * * 1,5"
  class: "ProductCustomizationJob"
  queue: product_customizations
  enabled: false

argentina_product_setup_job:
  cron: "0 23 * * 1,5"
  class: "ArgentinaProductSetupJob"
  queue: products_iteration
  enabled: false

chile_product_setup_job:
  cron: "0 23 * * 1,5"
  class: "ChileProductSetupJob"
  queue: products_iteration
  enabled: false
