categories_cleanup_job:
  cron: "0 1 * * *"
  class: "CategoriesCleanupJob"
  queue: cleanup
  enabled: false

products_cleanup_job:
  cron: "10 1 * * *"
  class: "ProductsCleanupJob"
  queue: cleanup
  enabled: false

categories_setup_job:
  cron: "5 1 * * *"
  class: "CategoriesSetupJob"
  queue: categories
  enabled: false

products_iteration_job:
  cron: "30 1 * * *"
  class: "ProductsIterationJob"
  queue: products_iteration
  enabled: false

attachments_fix_job:
  cron: "0 4 * * *"
  class: "AttachmentsFixJob"
  queue: attachments_fix
  enabled: false

products_update_price_job:
  cron: "0 3 * * *"
  class: "ProductsUpdatePriceJob"
  queue: products_iteration
  enabled: false

product_customization_job:
  cron: "0 5 * * 1,5"
  class: "ProductCustomizationJob"
  queue: product_customizations
  enabled: false