development:
  bigcorp_api: https://rfy56yfcwk.execute-api.us-west-1.amazonaws.com/bigcorp/employees?

test:
  bigcorp_api: https://rfy56yfcwk.execute-api.us-west-1.amazonaws.com/bigcorp/employees?

production:
  bigcorp_api: <%= ENV["BIGCORP_API"] %>
